Dependencies:
 - 'on': ['Linux', 'FreeBSD']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'plasma/plasma-activities': '@same'
    'plasma/kactivitymanagerd': '@same'

Options:
 test-before-installing: True
 require-passing-tests-on: ['Linux', 'FreeBSD']
